import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  wrapper: {
    flex: 1,
    margin: 0,
    padding: 0,
    backgroundColor: '#fff',
  },
  loginWrapper: {
    flex: 1,
    justifyContent: 'space-between',
    margin: 0,
    padding: 0,
    backgroundColor: '#fff',
  },
  getStartedText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  logoHeader: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 50,
  },
  homeBody: {
    flex: 2,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionSide: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  homeBodyOptions: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionSideOptions: {
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  map: {
    width: '100%',
    height: '100%',
  },
  homeText: {
    textAlign: 'center',
  },
  signupBtn: {
    width: '80%',
    backgroundColor: '#1E90FF',
    borderRadius: 8,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  loginBtn: {
    width: '80%',
    backgroundColor: 'coral',
    borderRadius: 8,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    padding: 10,
    borderRadius: 6,
    marginTop: 20,
    width: '80%',
  },
  dobContainer: {
    flexDirection: 'row',
    width: '80%',
    justifyContent: 'space-between',
  },
  signupLogo: {
    width: 100,
    height: 100,
  },
  ddInput: {
    borderWidth: 1,
    width: '20%',
    alignItems: 'center',
    borderColor: '#ddd',
    padding: 10,
    borderRadius: 6,
    marginTop: 20,
    marginRight: 5,
    textAlign: 'center',
  },
  mmInput: {
    borderWidth: 1,
    width: '30%',
    alignItems: 'center',
    borderColor: '#ddd',
    padding: 10,
    borderRadius: 6,
    marginTop: 20,
    marginRight: 5,
    textAlign: 'center',
  },
  yyInput: {
    borderWidth: 1,
    width: '40%',
    alignItems: 'center',
    textAlign: 'center',
    borderColor: '#ddd',
    padding: 10,
    borderRadius: 6,
    marginTop: 20,
    marginRight: 5,
  },
  loginTitle: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#1E90FF',
    alignItems: 'center',
    textAlign: 'center',
    marginTop: 20,
  },
  signupTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1E90FF',
    alignItems: 'center',
    textAlign: 'center',
    marginTop: 20,
  },
  bottomDiv: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    marginRight: 30,
    marginBottom: 20,
  },
  forgotDiv: {
    marginTop: 20,
    justifyContent: 'flex-start',
    marginLeft: 20,   
    alignItems: 'flex-start',
  },
  loginForgotPassword: {
    color: '#1E90FF',    
  },
  signupTextFromLogin: {
    marginBottom: 20,
    fontWeight: 'bold',
    color: '#1E90FF',
  },
  loginTestButton: {
    color: '#fff',
    fontWeight: 'bold',
  },
  LoginButton: {
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    backgroundColor: 'coral',
    width: '80%',
  },
  loginForm: {
    justifyContent: 'center',
    alignItems: 'center',
  },
});
