import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  camera: {
    width: "100%",
    height: "100%",
    marginTop: 0,
  },
  deleteButton: {
    alignContent: "flex-end",
    alignItems: "flex-end",
  },
  deleteButtonContainer: {
    position: "absolute",
    top: 5,
    right: 5,
  },
  cameraWrapper: {
    borderWidth: 1,
    borderColor: "#ddd",
    marginBottom: 5,
    margin: 0,
    width: "90%",
    height: "50%",
  },
  image: {
    flex: 1,
    justifyContent: "center",
  },
  capturedImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  captureButtonContainer: {
    position: "absolute",
    bottom: 10,
    alignSelf: "center",
  },
  captureButton: {
    backgroundColor: "coral",
    padding: 15,
    borderRadius: 50,
  },
  hiddenField: {
    display: "none",
  },
  mapLoading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  claimContainer: {
    flex: 1,
    backgroundColor: "#fff",
  },
  claimWrapper: {
    backgroundColor: "#fff",
  },
  wrapper: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  loginWrapper: {
    flex: 1,
    justifyContent: "flex-start",
    backgroundColor: "#fff",
  },
  getStartedText: {
    color: "#707073",
    fontWeight: "bold",
    fontSize: 16,
  },
  logo: {
    width: "40%",
    height: "30%",
    resizeMode: "contain",
    marginBottom: 20,
  },
  headerTitle: {
    color: "#fff",
    fontWeight: "bold",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 20,
  },
  leftIcon: {
    marginLeft: 10,
    marginTop: 10,
  },
  modal: {
    width: "100%",
    height: "20%",
    backgroundColor: "#5E2BFF",
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingTop: 20,
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  modalFly: {
    width: "60%",
    height: "40%",
    backgroundColor: "#5E2BFF",
    position: "absolute",
    top: "10%",
    right: 20,
    borderRadius: 25,
  },
  headerContainer: {
    height: "13%",
    width: "100%",
    backgroundColor: "#612cfe",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  button: {
    borderRadius: 20,
    padding: 8,
    elevation: 2,
    width: "10%",
    alignItems: "center",
    justifyContent: "center",
    bottom: 10,
    marginTop: 6,
    left: 10,
  },
  buttonOpen: {
    backgroundColor: "#fff",
  },
  buttonClose: {
    backgroundColor: "#fff",
  },
  analyticsIcon: {
    color: "#fff",
    fontWeight: "bold",
    marginRight: 10,
  },
  analytics: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 10,
  },
  topCategory: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 10,
  },
  header: {
    width: "100%",
    backgroundColor: "#612cfe",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
  },
  mapContainer: {
    height: "87%",
    width: "100%",
  },
  logoHeader: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 50,
  },
  homeBody: {
    flex: 2,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  actionSide: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  homeBodyOptions: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  actionSideOptions: {
    flex: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  homeText: {
    textAlign: "center",
    color: "#fff",
    fontSize: 22,
    padding: 20,
  },
  signupBtn: {
    width: "80%",
    backgroundColor: "#1e90ff",
    borderRadius: 8,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  textLeft: {
    textAlign: "left",
    width: "80%",
    marginLeft: 5,
    marginBottom: 3,
    color: "#fff",
    fontWeight: "bold",
  },
  loginBtn: {
    width: "50%",
    backgroundColor: "#fff",
    borderRadius: 27,
    height: 35,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  addButtonContainer: {
    position: "absolute",
    bottom: 20,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  addButton: {
    position: "absolute",
    bottom: 20,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  addArrow: {
    color: "#612cfe",
    fontWeight: "bold",
  },
  backArrow: {
    color: "#fff",
    marginLeft: 8,
  },
  rightIcon: {
    color: "#fff",
    marginRight: 8,
  },
  flyTitle: {
    justifyContent: "center",
    textAlign: "center",
    color: "#fff",
    fontWeight: "bold",
    marginTop: 5,
  },
  flyContainer: {
    marginTop: 10,
    width: "100%",
    maxHeight: "80%",
  },
  flyItem: {
    width: "95%",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#6d3dfc",
    borderRadius: 10,
    margin: 5,
    //height: 60,
    flexDirection: "row",
    paddingBottom: 10,
    maxHeight: "100%",
  },
  flyImageContainer: {
    width: "30%",
    marginRight: 3,
    aspectRatio: 1,
  },
  flyImage: {
    flex: 1,
    width: "30%",
    aspectRatio: 1,
    borderRadius: 6,
    width: undefined,
    height: undefined,
  },
  flyTextContainer: {
    width: "70%",
    height: 60,
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  flyText: {
    color: "#fff",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    paddingLeft: 5,
    borderRadius: 9,
    marginBottom: 10,
    backgroundColor: "#fff",
    width: "80%",
    height: 32,
  },
  inputModal: {
    borderWidth: 1,
    borderColor: "#ddd",
    paddingLeft: 10,
    borderRadius: 9,
    marginBottom: 10,
    backgroundColor: "#fff",
    width: "80%",
    height: 32,
    fontWeight: "bold",
  },
  dobContainer: {
    flexDirection: "row",
    width: "80%",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  signupLogo: {
    width: 100,
    height: 100,
  },
  ddInput: {
    borderWidth: 1,
    width: "20%",
    alignItems: "center",
    borderColor: "#ddd",
    borderRadius: 6,
    marginTop: 5,
    marginRight: 5,
    textAlign: "center",
    backgroundColor: "#fff",
  },
  mmInput: {
    borderWidth: 1,
    width: "30%",
    alignItems: "center",
    borderColor: "#ddd",
    borderRadius: 6,
    marginTop: 5,
    marginRight: 5,
    textAlign: "center",
    backgroundColor: "#fff",
  },
  yyInput: {
    borderWidth: 1,
    width: "40%",
    alignItems: "center",
    textAlign: "center",
    borderColor: "#ddd",
    borderRadius: 6,
    marginTop: 5,
    marginRight: 5,
    backgroundColor: "#fff",
  },
  loginTitle: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#1e90ff",
    alignItems: "center",
    textAlign: "center",
    marginTop: 20,
  },
  signupTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1E90FF",
    alignItems: "center",
    textAlign: "center",
    marginTop: 20,
  },
  bottomDiv: {
    marginTop: 0,
    justifyContent: "center",
    alignItems: "center",
    width: "80%",
  },
  forgotDiv: {
    marginTop: 0,
    justifyContent: "flex-start",
    alignItems: "flex-start",
    width: "80%",
  },
  loginForgotPassword: {
    textAlign: "left",
    width: "80%",
    marginLeft: 5,
    marginBottom: 3,
    color: "#fff",
    marginBottom: 10,
  },
  signupTextFromLogin: {
    color: "#fff",
    justifyContent: "center",
    fontSize: 14,
  },
  loginTestButton: {
    color: "#fff",
    fontWeight: "bold",
  },
  LoginButton: {
    marginTop: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    backgroundColor: "coral",
    width: "80%",
  },
  bottomSpace: {
    marginTop: "20%",
  },
  loginForm: {
    justifyContent: "flex-start",
    alignItems: "center",
  },
  inputSelector: {
    borderWidth: 1,
    borderColor: "#ddd",
    padding: 10,
    borderRadius: 6,
    marginTop: 0,
    width: "100%",
  },
  border: {
    borderWidth: 1,
    borderColor: "#ddd",
    marginBottom: 5,
    margin: 0,
    width: "90%",
  },
  inputComment: {
    borderWidth: 1,
    borderColor: "#ddd",
    padding: 10,
    marginTop: 0,
    width: "90%",
  },
});
