import { StyleSheet, Dimensions } from "react-native";
const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;

const calloutWidthPercentage = 75;
const calloutHeightPercentage = 40;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  startContainer: {
    flex: 1,
    justifyContent: "center",
  },
  camera: {
    width: "100%",
    height: "100%",
    marginTop: 0,
  },
  deleteButton: {
    alignContent: "flex-end",
    alignItems: "flex-end",
  },
  deleteButtonContainer: {
    position: "absolute",
    top: 5,
    right: 5,
  },
  imagesClaimSubmitContainer: {
    borderWidth: 1,
    borderColor: "#5e2bff",
    marginBottom: 10,
    marginTop: 10,
    width: "90%",
    borderRadius: 6,
    flexDirection: "row",
  },
  imagesClaimSubmit: {
    margin: 0,
    width: "50%",
    borderRadius: 6,
    aspectRatio: 1,
  },
  cameraWrapper: {
    borderWidth: 1,
    borderColor: "#ddd",
    marginBottom: 5,
    margin: 0,
    width: "100%",
    height: "100%",
  },
  image: {
    flex: 1,
    justifyContent: "center",
  },
  capturedImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  capturedImageClaim: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
    aspectRatio: 1,
  },
  capturedImageClaimMap: {
    width: 100,
    height: 100,
    resizeMode: "contain",
  },
  captureButtonContainer: {
    position: "absolute",
    bottom: 10,
    alignSelf: "center",
  },
  captureButtonContainerAction: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "40%",
    position: "absolute",
    bottom: 10,
    alignSelf: "center",
  },
  icon: {
    fontWeight: "bold",
    fontSize: 24,
    color: "#fff",
    backgroundColor: "#612cfe",
    padding: 5,
    borderRadius: 6,
  },
  captureButton: {
    backgroundColor: "#612cfe",
    padding: 15,
    borderRadius: 50,
  },
  captureButtonSubmit: {
    backgroundColor: "#612cfe",
    padding: 15,
    borderRadius: 6,
  },
  captureButtonSubmitIcon: {
    backgroundColor: "#612cfe",
    padding: 7,
    borderRadius: 6,
  },
  hiddenField: {
    display: "none",
  },
  mapLoading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  claimContainer: {
    flex: 1,
    backgroundColor: "#fff",
  },
  claimWrapper: {
    backgroundColor: "#fff",
  },
  makeClaimWrapper: {
    justifyContent: "center",
  },
  startWrapper: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  wrapper: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  loginWrapper: {
    flex: 1,
    justifyContent: "flex-start",
    backgroundColor: "#fff",
  },
  getStartedText: {
    color: "#707073",
    fontWeight: "bold",
    fontSize: 16,
  },
  logo: {
    width: "50%",
    height: "40%",
    resizeMode: "contain",
    marginBottom: 20,
  },
  headerTitle: {
    color: "#cfd1cf",
    fontWeight: "bold",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 18,
  },
  headerTitleActive: {
    color: "#fff",
    fontWeight: "bold",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 20,
    textDecorationLine: "Underline",
  },
  claimsContainer: {
    width: "100%",
    height: "66%",
    position: "relative",
  },
  cameraIcon: {
    backgroundColor: "#612cfe",
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 8,
    borderRadius: 15,
    position: "absolute",
    top: "12%",
  },
  cameraIconStyling: {
    color: "#fff",
    fontSize: 30,
  },
  leftIcon: {
    marginLeft: 10,
    marginTop: 10,
  },
  modal: {
    width: "100%",
    height: "24%",
    backgroundColor: "#5e2bff",
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingTop: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  modalFly: {
    width: "100%",
    height: "100%",
  },
  headerContainer: {
    width: "100%",
    height: "14%",
    backgroundColor: "#5E2BFF",
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    paddingTop: 20,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  button: {
    borderRadius: 20,
    padding: 8,
    elevation: 2,
    width: "10%",
    alignItems: "center",
    justifyContent: "flex-start",
    bottom: 10,
    marginTop: 6,
    left: 10,
  },
  buttonOpen: {
    backgroundColor: "#fff",
  },
  black: {
    color: "#000",
  },
  buttonClose: {
    backgroundColor: "#fff",
  },
  white: {
    color: "#fff",
  },
  analyticsIcon: {
    color: "#fff",
    fontWeight: "bold",
    marginRight: 10,
  },
  instructionsView: {
    padding: 6,
    borderColor: "#fff",
    borderWidth: 1,
    borderRadius: 10,
  },
  instruction: {
    color: "#fff",
    fontWeight: "bold",
  },
  analytics: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 10,
  },
  topCategory: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 10,
  },
  header: {
    width: "100%",
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    paddingVertical: 10,
    paddingLeft: 10,
    paddingRight: 10,
    borderBottomColor: "#cfd1cf",
    borderBottomWidth: 2,
  },
  explore: {
    color: "#fff",
    fontWeight: "bold",
  },
  mapContainer: {
    height: "83%",
    width: "100%",
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
  },
  calloutContainer: {
    padding: 5,
    backgroundColor: "#5e2bff",
    borderRadius: 8,
    width: (windowWidth * calloutWidthPercentage) / 100,
    height: (windowHeight * calloutHeightPercentage) / 100,
  },
  calloutTitle: {
    fontSize: 16,
    fontWeight: "bold",
  },
  calloutDescription: {
    fontSize: 14,
  },
  containinerLoading: {
    height: "100%",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  mapContainerClaim: {
    height: "100%",
    width: "100%",
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
  },
  logoHeader: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 50,
  },
  homeBody: {
    flex: 2,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  actionSide: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  homeBodyOptions: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  actionSideOptions: {
    flex: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  homeText: {
    textAlign: "center",
    color: "#fff",
    fontSize: 22,
    padding: 20,
  },
  signupBtn: {
    width: "80%",
    backgroundColor: "#1e90ff",
    borderRadius: 8,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  textLeft: {
    textAlign: "left",
    width: "80%",
    marginLeft: 5,
    marginBottom: 3,
    color: "#fff",
    fontWeight: "bold",
  },
  textLeftClaimMarker: {
    textAlign: "left",
    width: "80%",
    marginLeft: 5,
    marginBottom: 3,
    color: "#fff",
    fontSize: 12,
  },
  loginBtn: {
    width: "50%",
    backgroundColor: "#fff",
    borderRadius: 27,
    height: 35,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  loginBtnClaim: {
    width: "50%",
    backgroundColor: "#5e2bff",
    borderRadius: 27,
    height: 35,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
  },
  addButtonContainer: {
    position: "absolute",
    bottom: 20,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  addButton: {
    position: "absolute",
    bottom: 20,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  addArrow: {
    color: "#612cfe",
    fontWeight: "bold",
  },
  backArrow: {
    color: "#fff",
    marginLeft: 8,
  },
  rightIcon: {
    color: "#fff",
    marginRight: 8,
  },
  flyTitle: {
    justifyContent: "center",
    textAlign: "center",
    color: "#5E2bff",
    fontSize: 20,
    marginTop: 5,
  },
  flyContainer: {
    marginTop: 10,
    width: "100%",
    maxHeight: "80%",
  },
  flyItem: {
    width: "95%",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    maxHeight: "100%",
  },
  flyItemContainer: {
    width: "100%",
    borderColor: "#cfd1cf",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    alignItems: "center",
  },
  NoContentFlyItemContainer: {
    width: "100%",
    alignItems: "center",
    height: "100%",
    justifyContent: "center",
  },
  flyImageContainer: {
    width: "20%",
    marginRight: 3,
    aspectRatio: 1,
  },
  flyImage: {
    flex: 1,
    width: "20%",
    aspectRatio: 1,
    borderRadius: 6,
    width: undefined,
    height: undefined,
    margin: 5,
  },
  flyTextContainer: {
    width: "100%",
    flexDirection: "column",
    alignItems: "flex-start",
    paddingLeft: 10,
  },
  flyText: {
    color: "#5E2bff",
    fontSize: 16,
  },
  flyTextClaims: {
    color: "#5E2bff",
    fontSize: 12,
  },
  NoClaimsFlyText: {
    color: "#5E2bff",
    fontSize: 16,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    paddingLeft: 5,
    borderRadius: 9,
    marginBottom: 10,
    backgroundColor: "#fff",
    width: "80%",
    height: 32,
  },
  inputModal: {
    borderWidth: 1,
    borderColor: "#ddd",
    paddingLeft: 10,
    borderRadius: 9,
    marginBottom: 10,
    backgroundColor: "#5E2bff",
    width: "80%",
    height: 32,
    fontWeight: "bold",
    color: "#fff",
  },
  inputModalClaimMarker: {
    borderWidth: 1,
    borderColor: "#ddd",
    paddingLeft: 10,
    borderRadius: 9,
    marginBottom: 5,
    backgroundColor: "#5e2bff",
    width: "40%",
    height: 25,
    color: "#fff",
    fontSize: 12,
  },
  inputModalClaimComment: {
    borderWidth: 1,
    borderColor: "#ddd",
    paddingLeft: 10,
    borderRadius: 9,
    marginBottom: 5,
    backgroundColor: "#5e2bff",
    width: "100%",
    color: "#fff",
    fontSize: 12,
  },
  markerGoup: {
    flexDirection: "row",
    width: "80%",
  },
  dobContainer: {
    flexDirection: "row",
    width: "80%",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  signupLogo: {
    width: 100,
    height: 100,
  },
  ddInput: {
    borderWidth: 1,
    width: "20%",
    alignItems: "center",
    borderColor: "#ddd",
    borderRadius: 6,
    marginTop: 5,
    marginRight: 5,
    textAlign: "center",
    backgroundColor: "#fff",
  },
  mmInput: {
    borderWidth: 1,
    width: "30%",
    alignItems: "center",
    borderColor: "#ddd",
    borderRadius: 6,
    marginTop: 5,
    marginRight: 5,
    textAlign: "center",
    backgroundColor: "#fff",
  },
  yyInput: {
    borderWidth: 1,
    width: "40%",
    alignItems: "center",
    textAlign: "center",
    borderColor: "#ddd",
    borderRadius: 6,
    marginTop: 5,
    marginRight: 5,
    backgroundColor: "#fff",
  },
  loginTitle: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#1e90ff",
    alignItems: "center",
    textAlign: "center",
    marginTop: 20,
  },
  signupTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1E90FF",
    alignItems: "center",
    textAlign: "center",
    marginTop: 20,
  },
  bottomDiv: {
    marginTop: 0,
    justifyContent: "center",
    alignItems: "center",
    width: "80%",
  },
  forgotDiv: {
    marginTop: 0,
    justifyContent: "flex-start",
    alignItems: "flex-start",
    width: "80%",
  },
  loginForgotPassword: {
    textAlign: "left",
    width: "80%",
    marginLeft: 5,
    marginBottom: 3,
    color: "#fff",
    marginBottom: 10,
  },
  signupTextFromLogin: {
    color: "#fff",
    justifyContent: "center",
    fontSize: 14,
  },
  loginTestButton: {
    color: "#fff",
    fontWeight: "bold",
  },
  LoginButton: {
    marginTop: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    backgroundColor: "coral",
    width: "80%",
  },
  bottomSpace: {
    marginTop: "20%",
  },
  loginForm: {
    justifyContent: "flex-start",
    alignItems: "center",
  },
  inputSelector: {
    borderWidth: 1,
    borderColor: "#ddd",
    padding: 10,
    borderRadius: 6,
    marginTop: 0,
    width: "100%",
  },
  border: {
    borderWidth: 1,
    borderColor: "#5e2bff",
    marginBottom: 5,
    margin: 0,
    width: "90%",
    borderRadius: 6,
  },
  inputComment: {
    borderWidth: 1,
    borderColor: "#5e2bff",
    padding: 10,
    marginTop: 0,
    width: "90%",
    borderRadius: 6,
  },
  textLeftClaim: {
    textAlign: "left",
    width: "90%",
    marginBottom: 3,
    color: "#5e2bff",
    fontWeight: "bold",
  },
});
